### PR TITLE
Shrinked font of compose message box

### PR DESCRIPTION
**Pull request by minervapanda**
Decreased the font size in chatbox.xml
d027fc60-89a2-11e6-890b-d03c8153a443

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@minervapanda, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by minervapanda** [comment]
@kunall17 Do you suggest any changes in this ?  Will this be merged now ?
Although ,I am working on my next contribution.

**Comment by kunall17** [comment]
@minervapanda looks good! 
@timabbott LGTM!

**Comment by timabbott** [comment]
Cool, merged as 18e839f7d7149b254a0ff920f423bc6e3c4164fe (I tweaked the commit message and added `Fixes #177.` so that it'd close the original issue automatically).  Thanks @minervapanda and @kunall17!

**Pull request closed without merging**
