### PR TITLE
Add an server option to the login screen

### PR DESCRIPTION
**Pull request by armooo**
Allow users to set a custom zulip server. We special case the URL format
of api.zulip.com to not include /api/.

### CODE REVIEW

**Comment by timabbott** [comment]
Awesome, thanks for doing this @armooo!!!   I guess you should tag this as fixing #1 :).  To what extent have you tested this?  @lfaraone can you review?

**Comment by armooo** [comment]
I have tested by this logging into my own zulip install. I don't have access to a zulip.com realm that supports password access so that flow is untested. I have a debug build that can be used to test on another realm. https://www.dropbox.com/s/ujk2usxpzro5qgx/zulip-debug.apk?dl=0

I have never been able to test the OAuth2 login flow on a local build. I think it requires the release signing key to work correctly. I also suspect this will not work with self hosted installs due to missing secrets.

**Comment by timabbott** [comment]
OK that seems pretty reasonable given the nature of the change; it'd be great to get the OAuth2 flow working anywhere other than zulip.com but I don't see a reason to block this PR on that...

**Comment by chauffer** [comment]
Seems nice, is this gonna merge?

**Comment by christian667** [comment]
Looks good, we need this as well, please merge and release soon :)

**Comment by SeMeKh** [comment]
Any progress on this one? We're pretty eager to see this PR land in `master`.

**Comment by magro** [comment]
+1

**Comment by bpereto** [comment]
+1

**Comment by willdeed** [comment]
+22

**Comment by GRbit** [comment]
+1

**Comment by timabbott** [comment]
@lfaraone I seem to recall you looked at this briefly and determined some changes were needed; but I don't remember the details, can you post them here?  Then one of the folks who are actively working on the project can take a look at finishing this...

**Comment by niftynei** [comment]
merged as a part of #52

**Pull request closed without merging**
