### PR TITLE
Added Material design

### PR DESCRIPTION
**Pull request by kunall17**
Hello @lfaraone While rebasing I was facing many conflicts so I created a new branch in my fork and split the commits (same commits as in PR #25 )

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by niftynei** [comment]
I ran this to see what the changes looked like. @kunall17 the text isn't legible on my phone (Nexus 5X running 6.0.1).  Is it visible on yours?

The actionbar color is vastly different from the original.  Not sure if this is a new color we're going for? pinging @lfaraone for his input.

Finally, the buttons for "compose private message" and "compose message to stream" are missing (pushed into the overflow menu). 


screenshot_20160401-121042
screenshot_20160401-121053
screenshot_20160401-121056
screenshot_20160401-121107
screenshot_20160401-121112
screenshot_20160401-121124
screenshot_20160401-121131

**Comment by kunall17** [comment]
Pushed some commits now  

**Screenshot on an API 22 device**
screenshot_2016-04-02-03-13-36


**Screenshot on an API 21 Device**
screenshot_2016-04-02-03-31-43

**Comment by kunall17** [comment]
Pushed one more commit which now changes the colors of the toolbar and status bar 

screenshot_2016-04-02-03-59-53

**Comment by niftynei** [comment]
super ceded by #35 . If there's changes in this PR that you'd like to include in the updated app, please re-submit a new PR.

**Pull request closed without merging**
