### PR TITLE
Fix:#328 Hide keyboard on swipe chatbox

### PR DESCRIPTION
**Pull request by vishwesh3**
PR addressing issue #328 

**Edit**
videotogif_2017 01 27_15 43 31

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@vishwesh3, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by Sam1301** [comment]
@vishwesh3 I think this can have an added complexity. Suppose the searchview is also open, then on swiping the chatbox, the keyboard will be closed but the user could have been typing in the search bar.

**Comment by vishwesh3** [comment]
@Sam1301 Done. Now if user is typing in searchview and swipes chatbox, keyboard is not hidden.
videotogif_2017 01 27_15 41 06

**Comment by Sam1301** [comment]
@vishwesh3 great, the code looks good to me :+1:

**Comment by timabbott** [comment]
@vishwesh3 I cleaned up your commit message to match our guidelines and merged this, thanks for fixing this quickly!
Check out the Zulip commit message guidelines for more details: https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages

**Comment by vishwesh3** [comment]
I will keep in mind next time. :)
Thanks for merging.

**Pull request closed without merging**
