### PR TITLE
Upgrade to Gradle 2.3, fix zulip/zulip-android#467.

### PR DESCRIPTION
**Pull request by maxymilianz**
We needed to upgrade to Gradle 2.3 for better functionality.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@maxymilianz, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by maxymilianz** [comment]
Some checks failed, but before I changed anything in the code, they were failing too. Anybody can help?

**Comment by kunall17** [comment]
the project build is failing

**Comment by maxymilianz** [comment]
@kunall17 I know, but isn't it normal? I mean, I've revoked all the changes I made and the ckecks still fail on my computer.

**Pull request closed without merging**
