### PR TITLE
Fix issue #206 : visibility of Toolbar on devices with api levels 19 or below 

### PR DESCRIPTION
**Pull request by sashafierce**
This PR addresses issue #206

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@sashafierce, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
- Squash the two commits 
- Append your single commit (after squash) message with `Fixes #206: ` so when this is merged the issue will be autoclosed!

**Comment by sashafierce** [comment]
Done.

**Comment by Sam1301** [comment]
Hi @sashafierce, the code looks fine to me, thanks for working on this :+1:

**Comment by timabbott** [comment]
Merged, thanks @sashafierce!!

**Pull request closed without merging**
