### PR TITLE
Fixes #325: Closes Soft Keyboard if it opens on activity recreation

### LINKED ISSUE #325: Keyboard keeps popping up when Theme is changed after typing a message
The keyboard does not hide after there is a change in theme when the user is typing the message. Then this keeps up in a cycle as and when i keep changing the theme.

g_20170125_0222423

@kunall17 @timabbott . I'd like to work on this.

### PR DESCRIPTION
**Pull request by nitish1211**
Fixes #325 

Here I am closing the keyboard if it remains open at startup.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@nitish1211, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Already there is a method https://github.com/nitish1211/zulip-android/blob/bcc4643fff3e8f80e38b5a07baa7b6d48c610657/app/src/main/java/com/zulip/android/activities/ZulipActivity.java#L615 use this one!

**Comment by nitish1211** [comment]
It does not work because `view=null` as the focus is not on any view(Usually when we use that method the focus is on the editText which is using it hence view wont be null) .So this check https://github.com/nitish1211/zulip-android/blob/bcc4643fff3e8f80e38b5a07baa7b6d48c610657/app/src/main/java/com/zulip/android/activities/ZulipActivity.java#L618 fails

**Comment by kunall17** [comment]
@nitish1211 ok makes sense! 

@timabbott LGTM!

**Comment by timabbott** [comment]
Merged as d3868cb4efbbcbb46680144a20aca428fc8b2e7a after tweaking the commit message style, thanks @nitish1211!

**Pull request closed without merging**
