### PR TITLE
Close streamdrawer on clicking item

### PR DESCRIPTION
**Pull request by Swati4star**
Closing the stream drawer after a stream item is selected

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Swati4star, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
This is weird, the streamDrawer is a expandable listView and this should expand (shows the topics in its stream) on clicking the item.
Expansion works on the production build deployed on play store! 

@Swati4star can you fix the bug causing this problem?

**Comment by Swati4star** [comment]
I just checked the expansion thing on playstore version.

@kunall17  Is there any branch on this code which is deployed to playstore?

**Comment by kunall17** [comment]
No, there is no other branch.
The playstore build is on d5f2ffc49b1c35202c5239f5bdf3332183cae225 so maybe you can check the code after this commit?

**Comment by Swati4star** [comment]
I will look into the problem!

**Comment by kunall17** [comment]
@Swati4star did you got the problem of expandableListView in streamsDrawer?

**Comment by Swati4star** [comment]
@kunall17 No, I am still looking into it.

**Comment by brainwane** [comment]
@Swati4star Please let us know if you need help figuring this out -- we can chat about it in https://zulip.tabbott.net/#narrow/stream/android .

**Comment by niftynei** [comment]
@Swati4star can you explain what issue or problem that this PR is aiming to fix?  Provide a screenshot or explanation of the bug that this PR addresses or a link to an issue #.  That'll make it easier to review. 

Thanks!

**Comment by Swati4star** [comment]
The problem right now is...streams drawer doesn't expand when we click on an item.

**Comment by timabbott** [comment]
@saketkumar95 now that we have a reproducer for the issue; can you test this PR?  I think it just got lost in October...

**Comment by saketkumar95** [comment]
@timabbott I think this PR should be closed. Clicking on the textView of the stream name the drawer will close itself. And streamsDrawer is supposed to work like this only.

@kunall17 what are your thoughts?

**Comment by kunall17** [comment]
Yup can be closed!

**Pull request closed without merging**
