### PR TITLE
Auto cancel the PhotoViewActivity download notification

### PR DESCRIPTION
**Pull request by saketkumar95**
**Summary of changes**

Automatically dismiss the notification of "Download Complete" after clicking on it. 

Screenshots or a brief video showing the change in action:

videotogif_2017 02 10_06 33 56

- [x] Code is formatted.

- [x] Run the lint tests with `./gradlew lintDebug` and make sure BUILD is SUCCESSFUL

- [x] Commit messages are well-written.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@saketkumar95, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Reword the commit and specify to autocancel the download notification, it's confusing with the GCM notifications!

**Comment by Sam1301** [comment]
@saketkumar95 Thanks for working on this, can you please reword the commit message to clarify where the change is made (eg: in PhotoViewActivity). Also the commit messages end with a period. Checkout the [commit message](https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages) guideline for more details.

**Comment by saketkumar95** [comment]
@Sam1301 Is this fine now? :)

**Comment by Sam1301** [comment]
Thanks for making that clear :+1: , also you missed the period at the end of sentence. Checkout this [example](https://github.com/zulip/zulip/commit/cd5b38f5d8bdcc1771ad794f37262a61843c56c0) for how a good commit message looks like.
Thanks!

**Comment by kunall17** [comment]
Added the '.' at the end and merged, thanks @saketkumar95 👍

**Pull request closed without merging**
