### PR TITLE
Updated font size in chatbox 

### PR DESCRIPTION
**Pull request by minervapanda**
reduced the font size of the compose message text

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@minervapanda, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Thanks for working on this, Two things

- Please consider to include a screenshot to easily see the difference, and get it merged faster
- Capitalize the Commit message [updated chatbox.xml r -> Updated chatbox.xml] and also remove the newline in between

And also next step would be to implement something like this 

Taken from open source library - https://github.com/splitwise/TokenAutoComplete
This would be awesome step! 
+ Also consider migrating to Names as currently we store the E-Mails in the AutoCompleteTextView!

**Comment by minervapanda** [comment]
@kunall17 . I will take care.Looking forward to try on implementing what you suggested.

**Comment by kunall17** [comment]
@minervapanda can you 

- Remove changes in the last line https://github.com/zulip/zulip-android/pull/191/commits/db982559b243182bbabf57ad17c5807aed8dcb33#diff-1aa14d72906ab9210b981e2facd2c1b1L91 in this commit 

- Capitalize the Commit message [updated chatbox.xml r -> Updated chatbox.xml]
- Remove the newline in between the commit message

So that we can merge this in?

**Comment by minervapanda** [comment]
@kunall17 should i send a fresh pr ?

**Comment by kunall17** [comment]
No, you could just amend the last commit and force push to make changes to the branch on which this PR is based see here https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-the-Last-Commit

**Comment by minervapanda** [comment]
I have already capitalised commit message Updated font size in chatbox #191
Sorry ,I could not get you what do I need to change in next line ?

**Comment by minervapanda** [comment]
Is that okay now @kunall17 ?

**Comment by kunall17** [comment]
Na you have 3 commits in this PR now, try squashing them https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits which uses **git rebase** 
 https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

**Comment by minervapanda** [comment]
@kunall17  As changes were small , I made the changes after forking by editing the file, not in the local repository .

**Comment by kunall17** [comment]
No for squashing and rebasing you need to use the command line tools in your local repo and push into the branch!

**Comment by minervapanda** [comment]
remote: Permission to zulip/zulip-android.git denied to minervapanda.
fatal: unable to access 'https://github.com/zulip/zulip-android.git/': The requested URL returned error: 403

This is the error I am getting. Help!

**Comment by Sam1301** [comment]
Hi @minervapanda 

> remote: Permission to zulip/zulip-android.git denied to minervapanda.
> fatal: unable to access 'https://github.com/zulip/zulip-android.git/': The requested URL returned error: 403

it seems as if you tried to commit to https://github.com/zulip/zulip-android.git/
Try committing to the local copy of your fork, then you can push the changes to your fork.

**Pull request closed without merging**
