### PR TITLE
Async get events patch

### PR DESCRIPTION
**Pull request by koziodigitalinc**
A patch surrounding this crashlytics issue:  https://fabric.io/zulip2/android/apps/com.zulip.android/issues/57b9c482ffcdc04250073531

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@koziodigitalinc, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by niftynei** [comment]
This lgtm. Can you clean up the commit history for this PR? Thanks!

**Comment by koziodigitalinc** [comment]
@niftynei It's in regards to this: https://github.com/zulip/zulip-android/issues/148

This was before i started following your guidelines for pull requests. When i Squash this I will link the issue

**Comment by koziodigitalinc** [comment]
@niftynei  alright updated.

**Comment by niftynei** [comment]
Great. this has been mreged. thanks!

**Pull request closed without merging**
