### PR TITLE
Fixed Crash in API<21 due to tinting of drawables using ColorStateList.

### PR DESCRIPTION
**Pull request by nitish1211**
Fixed the crash in API<21 due to the tinting of drawables using [ColorStateList](https://developer.android.com/reference/android/content/res/ColorStateList.html) which here was `colorTextSecondary.xml`

1)Added a new Custom `TintableImageView.java` to allow lower APIs to use android tint feature with ColorStateLists.
2)Added a attribute `app:tint` to `TintableImageView`

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@nitish1211, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by nitish1211** [comment]
@Sam1301 Can you please review this? :slightly_smiling_face:

**Comment by saketkumar95** [comment]
@nitish1211 Kindly go through the commit messages guidlines :) https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages

**Comment by nitish1211** [comment]
@saketkumar95 Is this fine?

**Comment by saketkumar95** [comment]
@nitish1211 FYI, if you put Fixes: [#431](https://github.com/zulip/zulip-android/issues/431) in any of the commits of the PR, then issue would be automatically closed, so please include this if your PR fixes any existing issues! :)

**Comment by nitish1211** [comment]
@saketkumar95 Done. :)

**Comment by saketkumar95** [comment]
@nitish1211 Nice work! :) 
@kunall17 This looks good to me. You can have a quick review. :)

**Comment by kunall17** [comment]
I think we can use `android.support.v7.widget.AppCompatImageView` for this!  and use app:tint!

**Comment by nitish1211** [comment]
This is how its working with `android.support.v7.widget.AppCompatImageView`.

screenshot from 2017-03-06 22-02-13


`android.support.v7.widget.AppCompatImageView` supports [Background Tinting](https://developer.android.com/reference/android/support/v4/view/TintableBackgroundView.html) in which the tint is masked by the alpha channel of the drawable. The drawable’s color channels are thrown out so basically [SRC_IN](https://developer.android.com/reference/android/widget/ImageView.html#attr_android:tintMode) tint mode. I could use `android:tintMode` to change it to _SRC_ATOP_ but it requires min API 21.

When using app:tint in ImageView the tint mode by default is _SRC_ATOP_
screenshot from 2017-03-06 22-01-17

@kunall17 Your thoughts on this?

**Comment by kunall17** [comment]
How about using     
`        DrawableCompat.setTint();` ?

**Comment by nitish1211** [comment]
@kunal17 haven't used `DrawableCompat.setTint()` but have set the ColorStateList from inside the java code and it looks fine. Please review this. :)

**Comment by nitish1211** [comment]
@Sam1301 I have added tint colorStateList to `list_dialog.xml` but I believe `photo_edit.xml` doesn't need as it uses tinting with regular colors.

Also formatted the code in the **entire Module/Project**. :)

**Comment by nitish1211** [comment]
@Sam1301 As I stated above tinting with colorStateList causes issues in API<19 whereas in `photo_edit.xml` uses tinting with regular colors which does not cause any errors or crashes in all API levels.
So I think it does not need to be changed. :)

**Comment by Sam1301** [comment]
yeah right, I presumed that we must be using colorstatelist tinting in that file as well.

**Comment by Sam1301** [comment]
Awesome work, thanks @nitish1211 :+1:
Merged the first 2 commits as f6224f5208583b2dc5bd9e05f590984f62ce8a35. Added "Fixes: issue-no" in the end.

**Pull request closed without merging**
