### PR TITLE
Update gradle version to 2.2.3

### PR DESCRIPTION
**Pull request by yadav-rahul**
This PR updates gradle version to `2.2.3` from `2.2.0` to make Instant run faster.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@yadav-rahul, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
@kunall17 @Sam1301 can one of you review this?

**Comment by Sam1301** [comment]
Nice @yadav-rahul , thanks for working on this, the code looks fine to know :+1:

**Comment by timabbott** [comment]
Merged, thanks @yadav-rahul!

**Pull request closed without merging**
