### PR TITLE
Crash fix for null reference bug

### PR DESCRIPTION
**Pull request by Swati4star**
App crashes on clicking on a message, click back and reopening the app.
screenshot from 2016-10-01 17 19 56

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Swati4star, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@Swati4star, thanks for signing the CLA!

**Comment by kunall17** [comment]
@Swati4star couldn't reproduce the bug, but the code looks nice! 
But before merging this can you please reword the commit message, something related to this bug, for maintaining a good commit history?

**Comment by Swati4star** [comment]
@kunall17 I have reword the commit.
Is it fine now?

**Comment by Swati4star** [comment]
@kunall17 Can you merge it now?

**Comment by timabbott** [comment]
@Swati4star it looks like you just reworded the GitHub pull request title; you should actually edit the commit in your `Swati4star:master` branch and force-push the branch to edit the actual commit.  https://github.com/zulip/zulip/pull/1879 is a helpful (new and looking for feedback!) on how to use GitHub.

**Comment by Swati4star** [comment]
I have edited the commit message only.
Should I change it from "	fix null reference bug" to something else?

**Comment by timabbott** [comment]
Yep, check out the commit message docs in http://zulip.readthedocs.io/en/latest/version-control.html for details.

**Comment by kunall17** [comment]
@Swati4star well the solution for the problem looks fine to me, but why is the person name or email String is null in the first place?
Every person in the database has a name and email stored, so this NPE is weird i was trying to reproduce the error but couldn't, any specific thing you did after re opening the app? 

+ Please can you capitalize the commit reword [fix person.java->Fix person.java] I know its a pain!

**Comment by Swati4star** [comment]
Done with the change.

The person's name/email turns out to be null in the following scenario.
You click on a message. Press back button.
When you reopen the app, it crashes.

**Comment by kunall17** [comment]
@Swati4star ohk, I'll debug the app and try to reproduce this thing, till then I don't think we should merge this in!

**Comment by kunall17** [comment]
Got the issue this time!
@timabbott lgtm..

Thanks for working on this @Swati4star

**Comment by timabbott** [comment]
Merged, thanks @Swati4star and @kunall17!

**Comment by Swati4star** [comment]
Thanks @kunall17 @timabbott :+1:

**Pull request closed without merging**
