### PR TITLE
Fixes #320 : Retaining edittext's data on screen orientation resolved

### LINKED ISSUE #320: EditText's text disappearing on changing the screen orinentation in Login Activity
**Actual Behaviour**

videotogif_2017 01 23_23 40 58

**Expected Behaviour**
The EditText should retain its text on changing the screen orientation.

@Sam1301 @timabbott @kunall17 Hi, I would like to work on this. Can I send the PR for the same?

### PR DESCRIPTION
**Pull request by harshitagupta30**
This PR addresses #320 

videotogif_2017 01 24_01 21 56

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@harshitagupta30, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by harshitagupta30** [comment]
@timabbott @Sam1301 @kunall17 Please review this PR.

**Comment by timabbott** [comment]
@harshitagupta30 please sign the Dropbox CLA; I imagine one of the other folks will review this soon.  Also CCing @saketkumar95.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@harshitagupta30, thanks for signing the CLA!

**Comment by kunall17** [comment]
Also Reword the commit to `Fixes #320:  Retaining edittext data on screen orientration resolved	`

**Comment by saketkumar95** [comment]
@timabbott It looks good to me. :) 
@kunall17 any suggestions?

**Comment by timabbott** [comment]
Merged, thanks @harshitagupta30!

**Pull request closed without merging**
