### PR TITLE
Implemented swipe to remove chatBox

### PR DESCRIPTION
**Pull request by kunall17**
record

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by niftynei** [comment]
nice!  works well afaict.  it's not the most discoverable functionality, but it definitely serves it's purpose. 👌

**Comment by kunall17** [comment]
Agreed, but this will be needed as after narrowing it will focus the message edit text and then the chat box won't go automatically on scrolling, so then hopefully user will try to swipe to remove chatBox

**Comment by niftynei** [comment]
💯  🌋

**Pull request merged**
