### PR TITLE
Fix key(fabricKey) not found in gradle

### PR DESCRIPTION
**Pull request by kunall17**
Fixes the  gradle error

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
Merged, thanks @kunall17!

@saketkumar95 can you confirm that this works now?

**Comment by saketkumar95** [comment]
@timabbott Yes, it's working now. :+1:

**Comment by timabbott** [comment]
Awesome, thanks for checking @saketkumar95!

**Pull request closed without merging**
