### PR TITLE
Bugfix api calls and gcm key

### PR DESCRIPTION
**Pull request by markusthegeek**
Needed to add slashes to all api calls as in "/v1/...". Also fix the problem with the empty current_key value that is now needed with the latest GMS service.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@markusthegeek, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@markusthegeek, thanks for signing the CLA!

**Comment by niftynei** [comment]
hey @markusthegeek thanks for the PR. What version of GMS does this problem crop up on?

**Comment by niftynei** [comment]
The root cause of this issue was a missing backslash in the parsing code for a user-provided domain. Issue is fixed in #78 .

I believe that #70 allow us to remove the `google-services.json`, rendering the empty API key issue moot.  If this isn't the case, we can re-open this suggested fix.

Thanks!

**Pull request closed without merging**
