### PR TITLE
Use ormlite queryRaw instead of queryBuilder.

### PR DESCRIPTION
**Pull request by Sam1301**
This pr solves release build crash 50.
Occasionally, Ormlite queryBuilder is giving wrong results for equality in `getByEmail()` Person.java 
Steps to replicate this crash:
- Uninstall and then reinstall the app to destroy existing database.
- Use dev environment to login.
- Select a new user and see if a crash occurs during loading messages
- If crash doesn't occur for one user try using another user.

I have tested this thoroughly and logged the values of email passed to the function and Person object returned. In cases of error, Person object returned totally different `Person.email` from the email that was passed to it for equality.

To solve this I have reverted back to using rawQuery method of ormlite library.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Sam1301, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
So this PR is for this stackTrace 
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.RuntimeException: java.sql.SQLException: Transaction callable threw non-SQL exception
       at com.zulip.android.models.Message.createMessages(Message.java:428)
       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:219)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.sql.SQLException: Transaction callable threw non-SQL exception
       at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:251)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:169)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
       at com.zulip.android.models.Message.createMessages(Message.java:414)
       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:219)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.RuntimeException: java.sql.SQLException: Unable to run update stmt on object com.zulip.android.models.Person@188b9b1a: UPDATE `people` SET `avatarUrl` = ?, `email` = ?, `isActive` = ?, `isBot` = ?, `name` = ? WHERE `id` = ?
       at com.j256.ormlite.dao.RuntimeExceptionDao.update(RuntimeExceptionDao.java:290)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:206)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:214)
       at com.zulip.android.models.Message$1.call(Message.java:420)
       at com.zulip.android.models.Message$1.call(Message.java:415)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:227)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:169)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
       at com.zulip.android.models.Message.createMessages(Message.java:414)
       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:219)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.sql.SQLException: Unable to run update stmt on object com.zulip.android.models.Person@188b9b1a: UPDATE `people` SET `avatarUrl` = ?, `email` = ?, `isActive` = ?, `isBot` = ?, `name` = ? WHERE `id` = ?
       at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25)
       at com.j256.ormlite.stmt.mapped.MappedUpdate.update(MappedUpdate.java:129)
       at com.j256.ormlite.stmt.StatementExecutor.update(StatementExecutor.java:472)
       at com.j256.ormlite.dao.BaseDaoImpl.update(BaseDaoImpl.java:409)
       at com.j256.ormlite.dao.RuntimeExceptionDao.update(RuntimeExceptionDao.java:287)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:206)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:214)
       at com.zulip.android.models.Message$1.call(Message.java:420)
       at com.zulip.android.models.Message$1.call(Message.java:415)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:227)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:169)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
       at com.zulip.android.models.Message.createMessages(Message.java:414)
       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:219)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.sql.SQLException: updating database failed: UPDATE `people` SET `avatarUrl` = ?, `email` = ?, `isActive` = ?, `isBot` = ?, `name` = ? WHERE `id` = ?
       at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
       at com.j256.ormlite.android.AndroidDatabaseConnection.update(AndroidDatabaseConnection.java:313)
       at com.j256.ormlite.android.AndroidDatabaseConnection.update(AndroidDatabaseConnection.java:188)
       at com.j256.ormlite.stmt.mapped.MappedUpdate.update(MappedUpdate.java:101)
       at com.j256.ormlite.stmt.StatementExecutor.update(StatementExecutor.java:472)
       at com.j256.ormlite.dao.BaseDaoImpl.update(BaseDaoImpl.java:409)
       at com.j256.ormlite.dao.RuntimeExceptionDao.update(RuntimeExceptionDao.java:287)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:206)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:214)
       at com.zulip.android.models.Message$1.call(Message.java:420)
       at com.zulip.android.models.Message$1.call(Message.java:415)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:227)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:169)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
       at com.zulip.android.models.Message.createMessages(Message.java:414)
       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:219)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: people.email (code 2067)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:553)
       at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
       at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
       at com.j256.ormlite.android.AndroidDatabaseConnection.update(AndroidDatabaseConnection.java:311)
       at com.j256.ormlite.android.AndroidDatabaseConnection.update(AndroidDatabaseConnection.java:188)
       at com.j256.ormlite.stmt.mapped.MappedUpdate.update(MappedUpdate.java:101)
       at com.j256.ormlite.stmt.StatementExecutor.update(StatementExecutor.java:472)
       at com.j256.ormlite.dao.BaseDaoImpl.update(BaseDaoImpl.java:409)
       at com.j256.ormlite.dao.RuntimeExceptionDao.update(RuntimeExceptionDao.java:287)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:206)
       at com.zulip.android.models.Person.getOrUpdate(Person.java:214)
       at com.zulip.android.models.Message$1.call(Message.java:420)
       at com.zulip.android.models.Message$1.call(Message.java:415)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:227)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:169)
       at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
       at com.zulip.android.models.Message.createMessages(Message.java:414)
       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:219)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

This didn't occur very frequently for me, but I got this error which is fixed by this PR!

**Comment by timabbott** [comment]
@kunall17 is that a positive review for merging this PR?  Or are you still planning to read the code more carefully?

**Comment by kunall17** [comment]
@timabbott because ORMlite internally is sometimes buggy, so there isn't much we can do, just use the rawQuery!
This isn't that frequent but we got one crash in crashlytics!

**Comment by timabbott** [comment]
Merged, thanks @Sam1301 and @kunall17!!

**Pull request closed without merging**
