### PR TITLE
Fix: Markdown render issues

### PR DESCRIPTION
**Pull request by Sam1301**
This pr addresses part of #272 .

- added support for strikethrough
- fixed formatting for inline code
- fixed formatting for code block
- added support for unordered/ordered lists
- added support for clickable span for #stream-name.

@kunall17 I'll send fixes for rest of the markdown issues in another pr.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Sam1301, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by Sam1301** [comment]
Screenshot and gif for changes :)


screenshot_20170207-215655
g_20170207_2158433

**Comment by timabbott** [comment]
Nice, this looks awesome!  Would be great if this got a review soon so we can include it in the release.

**Comment by kunall17** [comment]
Got this bug!

```
02-09 00:16:56.052 16585-16636/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                   Process: com.zulip.android.dev, PID: 16585
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.NumberFormatException: Invalid int: "*"
                                                       at java.lang.Integer.invalidInt(Integer.java:138)
                                                       at java.lang.Integer.parse(Integer.java:410)
                                                       at java.lang.Integer.parseInt(Integer.java:367)
                                                       at java.lang.Integer.parseInt(Integer.java:334)
                                                       at com.zulip.android.util.CustomHtmlToSpannedConverter.startSpan(CustomHtmlToSpannedConverter.java:248)
                                                       at com.zulip.android.util.CustomHtmlToSpannedConverter.handleStartTag(CustomHtmlToSpannedConverter.java:552)
                                                       at com.zulip.android.util.CustomHtmlToSpannedConverter.startElement(CustomHtmlToSpannedConverter.java:690)
                                                       at org.ccil.cowan.tagsoup.Parser.push(Parser.java:795)
                                                       at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1062)
                                                       at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1017)
                                                       at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:624)
                                                       at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
                                                       at com.zulip.android.util.CustomHtmlToSpannedConverter.convert(CustomHtmlToSpannedConverter.java:479)
                                                       at com.zulip.android.models.Message.formatContent(Message.java:367)
                                                       at com.zulip.android.ZulipApp$4.deserialize(ZulipApp.java:258)
                                                       at com.zulip.android.ZulipApp$4.deserialize(ZulipApp.java:231)
                                                       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                                                       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                                                       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
                                                       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
                                                       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
                                                       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
                                                       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
                                                       at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                                                       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                                       at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
                                                       at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:209)
                                                       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:156)
                                                       at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:25)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                       at java.lang.Thread.run(Thread.java:818) 
```

**Comment by kunall17** [comment]
Add some left, right padding in the code block! 
screen shot 2017-02-09 at 12 21 25 am

**Comment by Sam1301** [comment]
@kunall17 done the changes :) Added padding of 4dp for this :+1: 
screenshot_20170209-035359

**Comment by kunall17** [comment]
Merged, thanks @Sam1301 ! :) 👍

**Pull request closed without merging**
