### PR TITLE
Added progress dialog.

### PR DESCRIPTION
**Pull request by vishwesh3**
Show progress dialog while connecting
to server, refreshing, logging out.

Fix:#369

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@vishwesh3, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Also can you cover the dialog here https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/DevAuthActivity.java

**Comment by vishwesh3** [comment]
@kunall17 Done :)

**Comment by kunall17** [comment]
The offline indicator not appearing, fix this and will be merged next! :) 👍 

device-2017-02-09-003217

**Comment by vishwesh3** [comment]
Solved conflicts :) :+1:

**Comment by kunall17** [comment]
Merged, thanks @vishwesh3 ! :) 👍

**Pull request merged**
