### PR TITLE
Fix #230, added hardcoded strings in string.xml

### LINKED ISSUE #230: Hardcoding the strings in string.xml file.
There are many values / string which are hardcoded in the .xml file. It should be stored in the single file so that it can be accessed to the same text from anywhere in the app.
I would send the PR soon when i get assigned.

Can i work on this?? @timabbott @kunall17

### PR DESCRIPTION
**Pull request by abhaymaniyar**
**Summary of changes**

I simply added few strings in the string.xml and there were two tags with different key but same value, so I also corrected that.

Screenshots or a brief video showing the change in action:

Please make sure these boxes are checked before submitting your pull request - thanks! [Guide](./PULL_REQUEST_GUIDE.md)

- [x] Code is formatted.

- [x] Run the lint tests with `./gradlew lintDebug` and make sure BUILD is SUCCESSFUL

- [x] If new feature is implemeted then it is compatible with Night theme too.

- [x] Commit messages are well-written.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@abhaymaniyar, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by abhaymaniyar** [comment]
Oh sorry! my bad! @saketkumar95

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@abhaymaniyar, thanks for signing the CLA!

**Comment by saketkumar95** [comment]
@abhaymaniyar No problem! :)

**Comment by kunall17** [comment]
superseded by #424

**Pull request closed without merging**
