### PR TITLE
Convert server url to lowercase before connecting.

### PR DESCRIPTION
**Pull request by vishwesh3**
Fix:#345

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@vishwesh3, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
Why so much of code it could be easily achievable by changing here https://github.com/vishwesh3/zulip-android/blob/6b89888f82905f0055cd1127fb6f7beffdc59618/app/src/main/java/com/zulip/android/activities/LoginActivity.java#L278 and https://github.com/vishwesh3/zulip-android/blob/6b89888f82905f0055cd1127fb6f7beffdc59618/app/src/main/java/com/zulip/android/activities/LoginActivity.java#L287

**Comment by vishwesh3** [comment]
Thanks @kunall17 Done :)

**Comment by kunall17** [comment]
@timabbott LGTM!

**Comment by timabbott** [comment]
Merged as 16424033797ed1f09a758e0fdeace9d43c691d0c, thanks @vishwesh3!

**Pull request closed without merging**
