### PR TITLE
Hide soft keyboard when LoginActivity starts

### LINKED ISSUE #87: Google auth option is obscured by the text box to enter your email address
The text box that pops open when you arrive on the login page covers over the "Sign in with Google" option, which makes it hard to notice Google signup is available (since you have to hit the back button to see it).

### PR DESCRIPTION
**Pull request by kunall17**
Fixed #87

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by niftynei** [comment]
lgtm. works as advertised. 👍

**Comment by kunall17** [comment]
@niftynei the commit has not been merged,no code changes here! https://github.com/zulip/zulip-android/blob/master/app/src/main/AndroidManifest.xml#L39

**Comment by niftynei** [comment]
Thanks for pointing it out. This has been merged.

**Pull request closed without merging**
