### PR TITLE
Update build and connecting to development server instructions in Readme.

### PR DESCRIPTION
**Pull request by sashafierce**

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@sashafierce, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@sashafierce, thanks for signing the CLA!

**Comment by timabbott** [comment]
@kunall17 do you want to give this a review?

**Comment by kunall17** [comment]
Haven't tested this but looks good.. LGTM.. :)

**Comment by timabbott** [comment]
Cool, I made a few small tweaks to the language (and also reformatted the commit messages to match the Zulip style; check out the Zulip coding style guidelines here for more details: https://zulip.readthedocs.org/en/latest/code-style.html#version-control) and merged this.  Thanks @sashafierce!

**Pull request closed without merging**
