### PR TITLE
Add default activity transition animation class.

### PR DESCRIPTION
**Pull request by Sam1301**
**Summary of changes**

Added simple fade in/out activity transition animation in util folder and used it in photos feature, login and logout.

Example (during logout the animation looks like this)
g_20170208_0803193

- [x] Code is formatted.
- [x] Run the lint tests with `./gradlew lintDebug` and make sure BUILD is SUCCESSFUL

- [x] If new feature is implemeted then it is compatible with Night theme too.

- [x] Commit messages are well-written.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Sam1301, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by saketkumar95** [comment]
@Sam1301 for login/logout, i think we can use slide in/out animation. What do you think?

**Comment by Sam1301** [comment]
@saketkumar95 yeah, that'll be nice, what do you think our default activity transition animation across the app should be?

**Comment by saketkumar95** [comment]
@Sam1301 In my opinion , i think we should have a fast slide in on opening the activity and fast slide out too for closing or going back. Fade in/out are okay okay type. 
Will show you some examples if i get some on the internet. :)

**Comment by Sam1301** [comment]
ok, got your point, will make changes :)

**Comment by saketkumar95** [comment]
@Sam1301 Just a suggestion , instead of using `android.R.anim.fadein` you can create a new xml file in res/anim directory and keep the `android:duration="6000"` maybe it will be fast enough. :D

**Comment by saketkumar95** [comment]
@Sam1301 While re-designing the app UI. I've added some transition animation. Can i complete this PR in that only? If it's fine with you? :)

**Comment by Sam1301** [comment]
Ok sure, go ahead :+1:

**Comment by kunall17** [comment]
@Sam1301 what's the 35f1338 is about? (stacktrace if possible?)

**Comment by Sam1301** [comment]
I added this commit 35f1338 in #393 .

**Comment by kunall17** [comment]
I removed the commit 35f1338 and pushed the other commits! 

Merged, thanks 👍 @Sam1301 

@saketkumar95 now you can rebase to the master and use these commits from there!

**Pull request closed without merging**
