### PR TITLE
Added some build instructions to README.

### PR DESCRIPTION
**Pull request by maxblumental**
Instructions for adding google services conifg file and app id to the project.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@maxblumental, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/) and update the thread so we can consider merging your code.

**Comment by maxblumental** [comment]
Signed the CLA. Please consider my pull request.

**Comment by timabbott** [comment]
It'd be great to expand these instructions to include links to the "obvious" stuff of setting up an Android development environment so someone who hasn't done Android before at all but knows Java can contribute -- would you be up for doing that @maxblumental ?

**Comment by maxblumental** [comment]
By all means.
22 марта 2016 г. 7:01 пользователь "Tim Abbott" <notifications@github.com>
написал:

**Pull request merged**
