### PR TITLE
Added Loading dialog for devAuth

### LINKED ISSUE #80: Dev Backend button doesn't show errors
I have two suggestions for improvement with the Dev Backend button.

1) There's no spinner when you click on the "Dev Backend testing server" button to let you know that it's talking to the server. 
2) If there's any errors that occur after clicking "Dev Backend testing server", they aren't shown

cc @kunall17  :)

### PR DESCRIPTION
**Pull request by kunall17**
Fixed #80

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by niftynei** [comment]
lgtm!

**Comment by kunall17** [comment]
:+1:

**Comment by niftynei** [comment]
merged.

**Pull request closed without merging**
