### PR TITLE
Re-formatted whole project using the default code formatting

### PR DESCRIPTION
**Pull request by kunall17**
This basically re-formats and re-arranges the code lines according to android studio default code formatting,
For the new incoming PR's some have un-formatted code and if they use the formatting code command (To format the code they have written) it would format the whole current file therefore the commit includes changes in the code which they haven't touched,
So after this commit it would be easy for them to format code rather than selecting their changes and formatting them to avoid inclusion of git changes of other formatted code.
Hope this makes sense! :)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
@niftynei @Sam1301  what are your thoughts on this reformatting?  

If folks are on board with doing it I'm happy to merge, though I think we should clear the open PRs first since this will create a lot of merge conflicts.

**Comment by Sam1301** [comment]
I really like this idea. There are a lot of places in the project where code factoring is needed. While submitting new prs, people generally use built in shortcuts in Android studio for code factoring in android. But this also affects other places where changes were not made and hence messes up the git history. So, once this is merged we can use these shortcuts 👍

**Comment by timabbott** [comment]
OK.  I think we should do a coordinated effort to try to merge the useful open PRs and then do this, so as to avoid needing to merge the automated formatting changes with actual code changes :)

**Comment by kunall17** [comment]
Yeah, we should merge the rest of active PR's first! 
@Sam1301 can you review the #217 ?

**Comment by Sam1301** [comment]
Sure, will do this today :+1:

**Comment by timabbott** [comment]
I'm not sure that we're actually on track to have fewer open PRs; @kunall17 @saketkumar95 @Sam1301 should we change our strategy for this?

**Comment by kunall17** [comment]
I think we should merge this anyway, waiting for no open PR's would be a pain and practically very difficult to achieve.
If yes i would fix the merge conflicts we are getting!

**Comment by timabbott** [comment]
@saketkumar95 @Sam1301 what do you think?

**Comment by saketkumar95** [comment]
@timabbott Yeah @kunall17  is right . We should merge this soon because i guess there will be more open PRs in future and will achieving this after that will be a lot difficult.

**Comment by timabbott** [comment]
OK, sounds good, let's just get this in.

**Comment by kunall17** [comment]
Updated the branch! :)

**Comment by timabbott** [comment]
Merged, thanks @kunall17!  We should probably post comments on all the open PRs letting folks know we did this and they'll need to rebase.

**Pull request closed without merging**
