### PR TITLE
Fix: multiple asyncGetEvents

### LINKED ISSUE #121: Disconnected handler for queue
I'm not sure if this is an error in the server side or the android client and no other mobiles/web was connected to the server at this time!
I encountered this after exiting App 2-3 times and starting again then i start recieving these logs

**Disconnected handler for queue 1470980116:0** 

Log of the server - 
```
2016-08-12 01:38:44,947 INFO     127.0.0.1       GET     200  30ms (lp: 12.3s) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:46,761 INFO     127.0.0.1       GET     200  15ms (lp: 791ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:46,763 INFO     127.0.0.1       GET     200  14ms /api/v1/event                                                                                                                s [1470980116:0/0] [was connected] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:47,834 INFO     127.0.0.1       GET     200  22ms (lp: 40ms) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:47,837 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:48,586 INFO     127.0.0.1       GET     200  20ms (lp: 767ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:49,664 INFO     127.0.0.1       GET     200  21ms (lp: 434ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:49,667 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:50,695 INFO     127.0.0.1       GET     200  23ms (lp: 1.0s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:50,697 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:51,729 INFO     127.0.0.1       GET     200  13ms (lp: 1.0s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:51,732 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:52,392 INFO     127.0.0.1       GET     200  12ms (lp: 671ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:52,396 INFO     127.0.0.1       POST    200  65ms (db: 4ms/2q)                                                                                                                 /api/v1/messages/flags [add read/37] actually 0 (iago@zulip.com via ZulipAndroid                                                                                                                )
2016-08-12 01:38:53,436 INFO     127.0.0.1       GET     200   7ms (lp: 669ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:53,438 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:54,176 INFO     127.0.0.1       GET     200  12ms (lp: 747ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:54,413 INFO     127.0.0.1       POST    200  71ms (db: 3ms/2q)                                                                                                                 /api/v1/messages/flags [add read/10] actually 0 (iago@zulip.com via ZulipAndroid                                                                                                                )
2016-08-12 01:38:54,465 INFO     127.0.0.1       GET     200  11ms /api/v1/event                                                                                                                s [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:55,499 INFO     127.0.0.1       GET     200  17ms (lp: 268ms) /                                                                                                                api/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:55,503 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:56,543 INFO     127.0.0.1       GET     200  13ms (lp: 1.1s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:56,546 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)
2016-08-12 01:38:57,574 INFO     127.0.0.1       GET     200  15ms (lp: 1.0s) /a                                                                                                                pi/v1/events [1470980116:0/1] (iago@zulip.com via ZulipAndroid)
2016-08-12 01:38:57,580 INFO     Disconnected handler for queue 1470980116:0 (ia                                                                                                                go@zulip.com/ZulipAndroid)

```

@timabbott is this normal, or if error how to address this issue?

### PR DESCRIPTION
**Pull request by kunall17**
This should fix #121

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
To address this issue I dug this more, i found out while [initiating a new AsyncGetEvents](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/ZulipActivity.java#L1357) this [while loop](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncGetEvents.java#L101) in the run() of the Thread was still running and hence this thread stayed in state of running and was not picked up by garbage collector, hence if we stop this infinite loop the thread would go into the state of stopped or death state and let garbage collector to do its work! 
I tested the app several times, dumped the heap and did not notice any multiple getEvents!

**Comment by timabbott** [comment]
Awesome!

**Comment by niftynei** [comment]
lgtm. thanks @kunall17.

**Pull request closed without merging**
