### PR TITLE
Fixes #224 : Added color change in night mode

### LINKED ISSUE #224: Stream name background color should be dark Grey in night mode
The background color should be same as private messages header background color screenshot_20161024-152643

### PR DESCRIPTION
**Pull request by rhari991**
**Summary of changes**

Changed the stream name background color in night mode 
For #224 
screenshot_20170219-153851 1

Please make sure these boxes are checked before submitting your pull request - thanks! [Guide](./PULL_REQUEST_GUIDE.md)

- [x] Code is formatted.

- [x] Run the lint tests with `./gradlew lintDebug` and make sure BUILD is SUCCESSFUL

- [x] If new feature is implemeted then it is compatible with Night theme too.

- [x] Commit messages are well-written.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@rhari991, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@rhari991, thanks for signing the CLA!

**Comment by kunall17** [comment]
Hmmm, this is debatable, @timabbott @Sam1301 @vishwesh3 what would you prefer colors (current) or black in the stream name (message headers) ?

**Comment by Sam1301** [comment]
I'd prefer colors in message headers for dark theme.

**Comment by kunall17** [comment]
also @saketkumar95 

> what would you prefer colors (current) or black in the stream name (message headers) ?

**Comment by timabbott** [comment]
Yeah, we should definitely keep the colors in the headers; they're super useful for figuring out what you're looking at without having to read it.

**Comment by saketkumar95** [comment]
yeah, as everyone said. We should keep the colors only in the headers. They look good and useful for differentiating between other streams. :)

**Comment by vishwesh3** [comment]
Yeah, we should keep it, really helpful for differentiating streams.

**Pull request closed without merging**
