### PR TITLE
Search in narrowed view.

### PR DESCRIPTION
**Pull request by Sam1301**
Search should be performed in current narrow.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Sam1301, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
@Sam1301 fix the merge conflicts!

**Comment by Sam1301** [comment]
@kunall17 resolved the merge conflicts :+1:

**Comment by kunall17** [comment]
Works well! :) 👍 
@timabbott LGTM!

**Comment by timabbott** [comment]
Merged, thanks @Sam1301!

**Pull request closed without merging**
