### PR TITLE
Fix issue 178, behaviour of compose box.

### PR DESCRIPTION
**Pull request by reachme-ankita**
Made the behavior of compose box same over general, personal and stream level

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@reachme-ankita, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@reachme-ankita, thanks for signing the CLA!

**Comment by timabbott** [comment]
@kunall17 can you review this?

**Comment by kunall17** [comment]
@timabbott I replied to the message she sent here https://zulip.tabbott.net/#narrow/stream/android/topic/zulip-android.3A.20pull.20request.20193.3A.20Fix.20issue.20178.2C.20behaviour.2E.2E.2E

**Comment by brainwane** [comment]
@reachme-ankita As [Kunal said](https://zulip.tabbott.net/#narrow/stream/android/subject/zulip-android.3A.20pull.20request.20193.3A.20Fix.20issue.20178.2C.20behaviour.2E.2E.2E/near/32434):

> I haven't debugged your branch, to see what changes it does to the app!
> But also there are lot of unrelated changes in your commit 5813a4b + the commit history is also not right you should first fix those!
> And only commit 5813a4b should be there not 229d4d5 in your PR!

**Pull request closed without merging**
