### PR TITLE
Fixes #230 : Hardcoded the strings in strings.xml

### LINKED ISSUE #230: Hardcoding the strings in string.xml file.
There are many values / string which are hardcoded in the .xml file. It should be stored in the single file so that it can be accessed to the same text from anywhere in the app.
I would send the PR soon when i get assigned.

Can i work on this?? @timabbott @kunall17

### PR DESCRIPTION
**Pull request by saketkumar95**
This PR addresses [#230](https://github.com/zulip/zulip-android/issues/230)
Hardcoded the strings in strings.xml file and also  **@android:color/holo_blue_dark requires API level 14 (current min is 13)**
So overrided  resource in layout-v14

@timabbott @kunall17 Review and tell me if there any changes required. :)

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@saketkumar95, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by kunall17** [comment]
- Still there are many strings which are only used as placeholders
- Fixing holo color api issue should be in another commit
- Changes you have done does not fixes the holo colour issue!

**Comment by saketkumar95** [comment]
@kunall17 Can you point out other placeholders? I did almost which i found. Maybe i got missed.

**Comment by Sam1301** [comment]
@saketkumar95 Are u adding placeholders too to strings.xml? In case yes, then you run lint to see which hard coded placeholder strings are left in the project.

**Comment by Sam1301** [comment]
Hey @saketkumar95 It would be great if you can revive this pr since after it gets merged we can turn up the severity of hard-coded strings to error for the project.

**Comment by saketkumar95** [comment]
@Sam1301 Yes i will do it 2-3 days. I'm travelling now.  Little bit busy  with hackathons.  Will update you this soon. :)

**Comment by saketkumar95** [comment]
@kunall17 I'm closing this now! :)

**Pull request closed without merging**
