### PR TITLE
Migrated To Gradle

### PR DESCRIPTION
**Pull request by kunall17**
After all these commits the project is migrated to gradle, having targetSDKVersion 23, and running!
Upgraded Crashlytics to Fabric Crashlytics!

Commit Fixed Project (d2c37b8) deals with a 

- bug due to [Search View](https://github.com/zulip/zulip-android/blob/163e4ac0d64c0d4d12c0e15da7e9e87e12cb3341/src/com/zulip/android/ZulipActivity.java#L454-L479) 
- Now using GoogleApiClient.OnConnectionFailedListener
- And rest mostly are the formatting!

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@kunall17, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/) and update the thread so we can consider merging your code.

**Comment by kunall17** [comment]
Signed the Dropbox CLA!

**Comment by lfaraone** [comment]
Hi @kunall17 , thanks for the pull request. I've since moved the project to Gradle and pushed master. We aren't able to upgrade to Fabric Crashlytics just yet, so I've kept the embedded crashlytics.jar.

Right now, this PR combines several changes into one (see e.g. d2c37b8); it would be great if you could rebase off latest master and split out your commits per [https://zulip.readthedocs.org/en/latest/code-style.html#version-control Code Style: Version Control].

**Comment by timabbott** [comment]
@lfaraone I guess we should add a link to README.md for this project pointing to the overall Zulip version control docs?

**Comment by lfaraone** [comment]
Will do.

**Comment by ryansnowboarder** [comment]
@kunall17 thanks for not telling us to use Gradle 1.5 ;)

**Comment by lfaraone** [comment]
future changes in #27

**Pull request closed without merging**
