### PR TITLE
Grant uri permissions manually for mPhotoUri to support lower api levels.

### PR DESCRIPTION
**Pull request by Sam1301**
This pr addresses #306

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@Sam1301, it looks like you've already signed the Dropbox CLA. Thanks!

**Comment by timabbott** [comment]
@saketkumar95 @kunall17 can one of you review this?

**Comment by kunall17** [comment]
@timabbott I was waiting for the stacktrace from sashafierce in #306 to know issue better!

**Comment by yadav-rahul** [comment]
@timabbott I have physical device running on Android `4.1.2`. I am on it.

**Comment by yadav-rahul** [comment]
@Sam1301 @timabbott I tested this PR in Android `4.1.2` and is working fine now :tada:

**Comment by timabbott** [comment]
Great, merged, thanks @Sam1301  and @yadav-rahul!

**Pull request closed without merging**
